services:
  xdmod:
    build: .
    ports:
      - '8080:80'
    depends_on:
      - xdmod_db

  xdmod_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: xdmod_db
      MYSQL_USER: xdmod_user
      MYSQL_PASSWORD: xdmod_pass