services:
  xdmod_service:
    build: .
    ports:
      - '8080:80'
    depends_on:
      - xdmod_db

  xdmod_db:
    image: mysql:5.7
    command: --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ADMIN_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d